# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOj6lQtK3I4PFj3VSu-55mPIuCJ-hkcn
"""

import numpy as np

# Fix random seed
np.random.seed(42)

# Inputs
X = np.array([0.05, 0.10])

# Random weights from [-0.5, 0.5]
W_input_hidden = np.random.uniform(-0.5, 0.5, (2, 2))
W_hidden_output = np.random.uniform(-0.5, 0.5, (2, 2))

# Biases
b1 = 0.5   # hidden layer bias
b2 = 0.7   # output layer bias

# Activation function (tanh)
def tanh(x):
    return np.tanh(x)

# Forward pass

# Hidden layer
net_hidden = np.dot(W_input_hidden, X) + b1
out_hidden = tanh(net_hidden)

# Output layer
net_output = np.dot(W_hidden_output, out_hidden) + b2
out_output = tanh(net_output)

#  Results
print("Weights Input-Hidden:\n", W_input_hidden)
print("\nWeights Hidden-Output:\n", W_hidden_output)
print("\nHidden Layer Output:\n", out_hidden)
print("\nFinal Output of Network:\n", out_output)

